name: roboteacher_zimsec
description: "An educational platform for ZIMSEC curriculum with AI-powered learning"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.0.0

  # Local Storage & Offline Support
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0

  # Audio & Speech
  flutter_tts: ^3.8.3
  audioplayers: ^5.2.1

  # UI & Animations
  flutter_animate: ^4.2.0+1
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  confetti: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.2
  rive: ^0.12.4

  # Social Media Features
  image_picker: ^1.0.4
  video_player: ^2.7.2
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  graphview: ^1.2.0
  # flutter_webrtc: ^0.9.34

  # Internationalization
  intl: ^0.20.2

  # Firebase (commented for web build)
  # firebase_core: ^2.4.0
  # firebase_auth: ^4.2.0
  # cloud_firestore: ^4.3.0
  # firebase_storage: ^11.2.6

  # Payment (commented for local deployment)
  # flutter_stripe: ^9.2.0

  cupertino_icons: ^1.0.2
  file_picker: ^5.2.2
  csv: ^5.0.0
  go_router: ^13.2.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vocabulary_list.json
    # - assets/images/
    # - assets/animations/
    # - assets/sounds/
    # - assets/themes/
